### ISSUE TITLE
Request: Followup DI

### ISSUE THREAD

**Issue by MoSMaje** [jugeeya/UltimateTrainingModpack#193] opened 2021-02-19 05:39 UTC
It would be nice to have a secondary DI option. makes labbing Kill confirms and specific combo routes much much easier.

**Comment by jugeeya** [comment] 2022-05-11 17:47
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/99

**Closed by jugeeya** 2022-05-11 17:47 UTC
Labels: enhancement
