### ISSUE TITLE
Pokémon Trainer is still not working properly in 3.2

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#296] opened 2021-12-28 01:10 UTC
When loading the save state the Pokémon and the opponent respawn simultanously and THEN the PT switches to the corresponding Pokémon to it's position. So the CPU Player is already able to act, while PT is still switching.
https://drive.google.com/file/d/16Qf3GM51TE2MTw1pO4xhjf2UOIaAzCJd/view?usp=sharing

 PT will switch to the saved pokémon. In a mirror this also causes desyncs if the current Pokémon is not the saved Pokémon
https://drive.google.com/file/d/16WFqQG8NtEyXa7K9U7yPWLrpmR37B38i/view?usp=sharing

If saved and loaded pokémon are the same it actually works like you'd expect:
https://drive.google.com/file/d/16Svk1P_0rgABFLO-xZSVkERfVnfRsbXQ/view?usp=sharing

Another bug I found is that if you save the state, then use the standard training mode reset, and then load the state the opponent PT will actually not blow up until it's hit by an attack:
https://drive.google.com/file/d/16T5nudNG4VOnDiJ_gLPCkI-5ZXOOfY9l/view?usp=sharing

And a very crucial thing that is still not working is that loading save states makes one of the Pokémon unusable until training mode is reset:
https://drive.google.com/file/d/16dCcrVdnPNQWvnfDFiCDqRPntnVpUZ2h/view?usp=sharing

**Comment by asimon-1** [comment] 2021-12-28 02:26
The first three points are actually working as intended. The save state now also saves which pokemon was present, and will cycle the pokemon until it's back at the correct one before moving positions (for both the player and the CPU). This was necessary to account for the fact that PT cycles between pokemon on death automatically. The consequence is that when a save state involves a character in the air,  you have to wait until the cycling is complete to resume the training. I recommend keeping both fighters grounded for your save states and knocking them offstage after loading the state.

The last two are not intended. I think I understand the cause and will try to find a solution. A workaround is to avoid using the vanilla mode training reset between saving and loading states. You should also avoid saving a state with a non-PT character and loading it with PT, there will be similar issues.

**Comment by satoruneru** [comment] 2022-03-26 18:17
https://user-images.githubusercontent.com/102431615/160252234-fe7e7565-3c21-4a19-8e00-7334daf783db.mp4

**Comment by jugeeya** [comment] 2022-11-11 16:47
Finally, finally fixed in the beta with https://github.com/jugeeya/UltimateTrainingModpack/commit/4cb5152c289c7e53b464456735ac18e3cab15559

**Closed by jugeeya** 2022-11-11 16:47 UTC
Labels: bug
