### ISSUE TITLE
Bodyblocking sometimes gets deactivated when loading a save state

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#159] opened 2020-09-06 17:33 UTC
There are certain situation that remove body blocking when I load a save state.
https://i.imgur.com/pkoJOJO.jpeg

Loading save states during this situations have deactivated body blocking for me:
- During a Grab
- When bother fighters are in Hitlag
- Few frames after a hit

To fix this you have to do the following:
- hittting or L+R+Start reset
- Either character is hit
- if you load the save state during a grab, hitting a shield fixes it. If you load during a hit, hitting a shield doesn't fix it 

A KO does not fix this.

Tested on current beta

**Comment by jugeeya** [comment] 2020-09-06 18:28
Duplicate of #154

**Closed by jugeeya** 2020-09-06 18:28 UTC
