### ISSUE TITLE
Suggestion: Add a toggle to see how many frames your inputs are apart

### ISSUE THREAD

**Issue by RitualSSB** [jugeeya/UltimateTrainingModpack#501] opened 2023-03-01 04:41 UTC
IE: Be able to see how many frames you are off from EWGF, Snake Dashing, etc. Being able to see how many frames after you become actionable you press a button would be cool too (IE, How many frames after leaving jumpsquat etc.) wasn't sure the best place to suggest features, so figured here wasn't terrible.

**Comment by jugeeya** [comment] 2023-08-10 14:38
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/558

**Closed by jugeeya** 2023-08-10 14:38 UTC
