### ISSUE TITLE
menu problems during frame by frame (v3.0)

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#260] opened 2021-09-13 21:32 UTC
if you open the training mod menu during frame by frame and then close it, it will open again. This happens twice until the frame finally advances.

This doesn't happen if you hold the frame advance button (ZL) during the whole process but you have to re-press ZL after the menu closes. The game doesn't register the same button you were holding anymore after closing the menu.

**Comment by jugeeya** [comment] 2021-09-16 17:16
Duplicate of #257

**Closed by jugeeya** 2021-09-16 17:16 UTC
