### ISSUE TITLE
CPU will drop shield when attempting a shield grab, making it come out 7 frames slower

### ISSUE THREAD

**Issue by FlappyFalco** [jugeeya/UltimateTrainingModpack#34] opened 2019-12-04 19:01 UTC
The CPU will drop shield before inputting grab when attempting to shield grab if Mash Grab is enabled and their shield is hit. This is 7 frames slower than a true shield grab, making it very unreliable for checking if grab is a true punish on an attack.

**Comment by jugeeya** [comment] 2019-12-07 03:49
Yeah, I'm aware of this issue, it's quite weird, not sure why it's occurring. Definitely needs to be fixed before release.

**Comment by jugeeya** [comment] 2019-12-15 19:51
@solbarda Just letting you know, I MAY have figured this out? For shieldgrab, in the actual code it looks at category 2 commands even though the flag is a category 1... 

So since we only replace it for category 1, it doesn't work, so I'll try to replace it in the category 2 as well. 

https://github.com/jugeeya/UltimateTrainingModpack/blob/62442e7cae5644f910875c4cff8a6ef30f2ee742/source/training/mash.h#L51

Writing here to remind myself to test.

**Comment by jugeeya** [comment] 2019-12-16 03:57
@FlappyFalco Could you please test with the latest beta?

**Comment by solbarda** [comment] 2019-12-16 20:39
Will also try it out when I can, I have not yet full understanding of how the categories work, so I will try to work a little more on some debugging info.

**Comment by FlappyFalco** [comment] 2019-12-18 22:25
@jugeeya Did that beta fail to build? The latest beta is from 20 days ago and while the files dated within the ZIP are dated the 15th, there is no change in game, CPUs will still drop shield first before grabbing.

**Comment by jugeeya** [comment] 2019-12-22 00:34
Fixed beta builds just now, but apparently the issue is persisting anyways.

For reference, here is the code section in game that allows shieldgrabbing for researching this:
```cpp
if (WorkModule__get_int_impl(FIGHTER_INSTANCE_WORK_ID_INT_INVALID_CATCH_FRAME)) {
    if (WorkModule__is_enable_transition_term_impl(FIGHTER_STATUS_TRANSITION_TERM_ID_CONT_CATCH)) {
        // the following line is done every frame, not actually here but in a different function
        lua_state[30] = WorkModule::get_command_cat_flag_impl(1);
        if (lua_state[30] == FIGHTER_PAD_CMD_CAT1_FLAG_CATCH)) {
            // the following line is done every frame, not actually here but in a different function
            lua_state[22] = StatusModule::situation_kind_impl();
            if (lua_state[22] == SITUATION_KIND_GROUND) {
                if (!ItemModule__is_have_item_impl(0)) {
                    lua2cpp::L2CFighterBase::change_status(FIGHTER_STATUS_KIND_CATCH, 1);
                }
            }
        }
    }
}
```

which is why this is weird, there really aren't that many conditions we have to satisfy to get shieldgrabbing to work without dropping shield. Maybe `is_in_shieldstun` needs some work on our side? @solbarda

**Comment by jugeeya** [comment] 2019-12-22 00:37
At least, I think. Maybe we have to just do the `check_buton_on` checks, the code is actually quite long. Might do a full rewrite of the pseudocode when I can.

**Comment by jugeeya** [comment] 2020-05-14 22:29
Fixed in newest beta (releasing shortly).

**Closed by jugeeya** 2020-05-14 22:29 UTC
Labels: bug
