### ISSUE TITLE
Add option for random/mashing different di

### ISSUE THREAD

**Issue by nairauqa** [jugeeya/UltimateTrainingModpack#529] opened 2023-06-10 22:21 UTC
When kazuya lands ewgf on a character, the blue di lines of the opponent are able to be seen, it would help if there was a setting that mashed left and right di during the hitstun so that we could get simulate real counterplay against opponents who use this trick.

**Comment by GradualSyrup** [comment] 2023-08-12 17:28
Duplicate of #535

**Closed by GradualSyrup** 2023-08-12 17:28 UTC
