### ISSUE TITLE
Cannot save state of character being hit

### ISSUE THREAD

**Issue by comex** [jugeeya/UltimateTrainingModpack#198] opened 2021-04-10 21:47 UTC
If I save state while any character is:
- in hitlag
- in hitstun
- tumbling
- on the ground after missing a tech
- performing a getup option
then loading state puts the character in a neutral state instead.

I'm using Training Modpack 2.6 with Smash Ultimate 11.0.1.

**Comment by jugeeya** [comment] 2021-04-15 22:21
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/154

**Closed by jugeeya** 2021-04-15 22:21 UTC
