### ISSUE TITLE
Stale Queue doesn't reset

### ISSUE THREAD

**Issue by AZ-7** [jugeeya/UltimateTrainingModpack#69] opened 2020-05-18 22:36 UTC
As it is currently, the staleness queue upon resetting to a save state does not reset the stale queue as well. It would just be a nice QoL improvement if something like this were added for it to reset.

**Comment by jugeeya** [comment] 2020-05-18 23:31
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/61 , closing so discussion can be centralized there.

**Closed by jugeeya** 2020-05-18 23:31 UTC
