### ISSUE TITLE
Save State PT Switch

### ISSUE THREAD

**Issue by katykat5099** [jugeeya/UltimateTrainingModpack#206] opened 2021-05-30 05:33 UTC
Because character death when resetting save state, the character switches when unintended. Apparently causes other bugs too but mainly problem with pt and switching.

**Comment by bluesm0ke** [comment] 2021-06-20 22:37
This bug makes it so that the pokemon that is being used becomes super bugged after resetting the save state. Only a few of their moves have hitboxes, their animations are different, they have no landing lag on aerials, and more stuff. This bug can affect two of the pokemon at once, but never all 3.

**Comment by jugeeya** [comment] 2021-08-16 06:37
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/154

**Closed by jugeeya** 2021-08-16 06:37 UTC
