### ISSUE TITLE
Tesla Menu: "Could not debug process" (2.0)

### ISSUE THREAD

**Issue by Areidz** [jugeeya/UltimateTrainingModpack#70] opened 2020-05-20 08:31 UTC
I've just updated the Training pack to the newest version, and once I open Smash, it says "Could not debug process" in the tesla menu.

Attached image of the error.

![20200520102935](https://user-images.githubusercontent.com/8595185/82424057-f1202e00-9a84-11ea-91e4-b93a84079be0.jpg)

Thanks for the support and this great tool! :)

**Comment by jugeeya** [comment] 2020-05-20 15:01
Does this happen every time? Even after a reboot?

**Comment by Areidz** [comment] 2020-05-20 15:04
I tried to reboot to payload (Hekate 5.2.1) and the same happened. I'm going to try to erase the files and copy them again, and reboot the whole console to see if it keeps happening.

**Comment by jugeeya** [comment] 2020-05-20 17:45
Could you post your atmosphere/config files?

**Comment by Areidz** [comment] 2020-05-20 19:04
**BCT.ini**
```
BCT0
[stage1]
stage2_path = atmosphere/fusee-secondary.bin
stage2_mtc_path = atmosphere/fusee-mtc.bin
stage2_addr = 0xF0000000
stage2_entrypoint = 0xF0000000
```

**system_settings.ini**
```
[atmosphere]
;0=onlysavetogglesiftogglefileexists.
;forrestorationonnewgamelaunch.1=alwayssavetoggles,
dmnt_always_save_cheat_toggles=u8!0x0
dmnt_cheats_enabled_by_default=u8!0x0
enable_deprecated_hid_mitm=u8!0x0
enable_hbl_bis_write=u8!0x0
enable_hbl_cal_read=u8!0x0
fatal_auto_reboot_interval=u64!0x0
fsmitm_redirect_saves_to_sd=u8!0x0
power_menu_reboot_function=str!payload
[eupld]
upload_enabled=u8!0x0
[hbloader]
applet_heap_reservation_size=u64!0x8600000
applet_heap_size=u64!0x0
[ro]
ease_nro_restriction=u8!0x1

```

**Comment by Areidz** [comment] 2020-05-31 20:52
Still not working in 2.05. 

How could I help you with it? Could you add some debug code in "could not debug process" in the Tesla Overlay so I could give you more feedback?

Thanks!

**Comment by Craftyawesome** [comment] 2020-05-31 22:04
This sometimes happens to me, but restarting the game normally fixes it.

**Comment by jugeeya** [comment] 2020-06-01 17:02
@Areidz So, it happens every time? There isn't really any more information I could provide. I think it may be due to your Switch FW being below 10.0, is it possible for you to upgrade?

**Comment by Areidz** [comment] 2020-06-01 22:19
@jugeeya I've just updated to 10.0.3 and it's still not working. I'll try to clean up the bootloader + atmosphere just in case something is messed up. Anyway, the hitboxes are showed in training mode, so probably it's a problem with the overlay.

**Comment by jugeeya** [comment] 2020-06-16 15:17
@Areidz do you have other overlays such as Edizon or other homebrew running?

**Comment by Areidz** [comment] 2020-06-16 15:29
@jugeeya yes, I do have Edizon

**Comment by jugeeya** [comment] 2020-06-16 15:30
@Areidz I noticed I would get a similar issue when having opened the Edizon overlay beforehand, does it occur even if you don't do that?

**Comment by Areidz** [comment] 2020-06-16 22:59
I've just tried and even if I don't open the Edizon Overlay beforehand, it's working that way. Should I remove the Edizon overlay?

**Comment by jugeeya** [comment] 2020-06-17 00:37
It does work without opening it? Try removing it.

**Comment by Areidz** [comment] 2020-06-17 09:50
I erased EdiZon completely and it's still giving me the same error.

I'll try to reinstall everything from scratch in a couple of weeks and I'll report it again.

**Comment by jugeeya** [comment] 2020-09-09 15:55
Going to close this issue for now. Seems to be some setup-specific error that is hard to reproduce.

**Closed by jugeeya** 2020-09-09 15:55 UTC
