### ISSUE TITLE
Ice climbers are kinda borked.

### ISSUE THREAD

**Issue by Cydget** [jugeeya/UltimateTrainingModpack#165] opened 2020-09-26 22:03 UTC
Using save states causes nana to respawn at the top of the screen. Additionally, it causes nana to freeze in place after preforming a few desyncs. I could send a screenshot if you need, but it should be easy enough to reproduce.

**Comment by jugeeya** [comment] 2020-09-27 23:26
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/154

**Closed by jugeeya** 2020-09-27 23:27 UTC
