### ISSUE TITLE
Bayonetta Smash Attack Hitboxes

### ISSUE THREAD

**Issue by KingCalamity** [jugeeya/UltimateTrainingModpack#149] opened 2020-08-26 14:10 UTC
Bayonetta's up, down, and side smash attacks only have active hitboxes of about 2 to 3 frames according to ultimateframedata.com but the hitbox visualizer hows that they are active the entire time the animation is out.

**Comment by jugeeya** [comment] 2020-08-28 16:26
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/131 .

**Closed by jugeeya** 2020-08-28 16:26 UTC
