### ISSUE TITLE
Ice Climbers unusable

### ISSUE THREAD

**Issue by bah-WD** [jugeeya/UltimateTrainingModpack#209] opened 2021-06-30 03:42 UTC
I'm an Ice Climbers (IC) main and this modpack is basically unusuable for IC's. Nana's hitboxes don't register meaning hit the opponent or have part of the animation (i.e. blizzard), save state and activating reset causes Nana to appear at the top blast zone of the map and slowly fall down. Sometimes Nana is unresponsive and will stand there doing nothing. She does this sometimes on Kalos, but this is not platform position related. Even on FD Nana will stand there away from you doing nothing, which doesn't normally happen. Another bug is that Up-B causes you to fall to your death. Nana grabs the ledge first, as normal, and Popo goes up then never is able to successfully grab the ledge regardless of outside influence.

**Comment by SamJessop** [comment] 2022-01-29 08:48
Looks like alot of this was fixed in the latest version but there are still issue.

Opponents DI on dthrow seems very un stable, sometimes they will DI sometimes it just stops working and I can never get it to work again.

**Comment by GradualSyrup** [comment] 2022-02-04 02:52
Unsure of what exactly you mean by this down throw DI thing. In my personal use and those who I've asked, there doesn't appear to be an issue with the ICs in this regard. Did more testing and couldn't reproduce the issue either. I think this issue should be closed, as what is described in the initial issue post has been completely resolved by the save states patch. If the issue persists and you can reproduce it, you should create a new issue and describe a reproduction method if possible.

**Closed** 2022-02-06 00:12 UTC
