### ISSUE TITLE
Playback Recording

### ISSUE THREAD

**Issue by SaiyanMario** [jugeeya/UltimateTrainingModpack#116] opened 2020-07-28 21:13 UTC
Many if not all Fighting games have this feature called playback recording and I think the modpack would benefit a lot from it as it'll make it easier to lab against specific scenarios
Example: https://www.youtube.com/watch?v=6_7Tm2HjmyQ

**Comment by jugeeya** [comment] 2020-07-28 21:33
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/78 .

**Closed by jugeeya** 2020-07-28 21:33 UTC
