### ISSUE TITLE
The "switching save states" bind can be pressed way too easily

### ISSUE THREAD

**Issue by iceypotato** [jugeeya/UltimateTrainingModpack#503] opened 2023-03-07 23:52 UTC
I usually press the grab and the up taunt button when I want to reset, but sometimes I would accidentally switch save states when I press the up taunt key, because of how the pro controller dpad is. I know you are considering adding custom binds, but I feel like it is a little hard to practice with this already existing bind.

**Comment by zheskett** [comment] 2023-03-09 19:17
The binding should have to be held or something. On gcc its extremely finicky to just do save and load

**Comment by thepeternguyen** [comment] 2023-03-13 13:31
Experienced this same issue and thought I had done something wrong. It's a very useful tool to switch save states but I agree, binding could be held or maybe the "switching save states" feature can be toggled on/off. Was much smoother before.

**Comment by jugeeya** [comment] 2023-03-14 05:24
Could you folks try the latest beta? I added an enabler toggle as well as changed the binding to Shield+Left/Right Taunt for switching save state slots. https://github.com/jugeeya/UltimateTrainingModpack/releases/tag/beta

**Comment by iceypotato** [comment] 2023-03-14 19:15
Yep did that, no change. I am pretty sure I am on the beta because I do see a save slots button.

**Comment by Bunny5001** [comment] 2023-03-16 04:36
> Could you folks try the latest beta? I added an enabler toggle as well as changed the binding to Shield+Left/Right Taunt for switching save state slots. https://github.com/jugeeya/UltimateTrainingModpack/releases/tag/beta

This doesn't do anything because the bind still uses the taunt buttons which is the problem because it just switches save states  when trying to load new ones even if you don't press left or right taunt in my experience

**Comment by jugeeya** [comment] 2023-03-23 16:29
I just switched the binds in the latest beta. 

> Save State Save: Shield+DPad Down
> Save State Load: Shield+DPad Up
> Save State Next Slot: Grab+DPad Left
> Save State Prev Slot: Grab+DPad Right

Could you all delete `sd:/ultimate/TrainingModpack/training_modpack.toml` and retry?

**Comment by Bunny5001** [comment] 2023-03-24 02:32
I tried and its still the same issue because the problem is not the shield or grab button, its the Dpad. The Dpad messes everything up because game cube controllers are stupid and read multiple inputs if you aren't pressing it with the utmost precision (at least this is how I think it works) . The only way to fix it is by making it a keybind that doesn't use the DPad which I assume would be pretty hard considering that most people have buttons mapped to everything else. I'll work around it, thank you for trying to solve it though

**Comment by Bunny5001** [comment] 2023-03-24 02:42
> I just switched the binds in the latest beta.
> 
> > Save State Save: Shield+DPad Down
> > Save State Load: Shield+DPad Up
> > Save State Next Slot: Grab+DPad Left
> > Save State Prev Slot: Grab+DPad Right
> 
> Could you all delete `sd:/ultimate/TrainingModpack/training_modpack.toml` and retry?

It works, is there any way to make it to grab + Dpad down and up doesn't also save and load states so there aren't redundant keybinds?

**Comment by iceypotato** [comment] 2023-03-29 17:02
> I just switched the binds in the latest beta.
> 
> > Save State Save: Shield+DPad Down
> > Save State Load: Shield+DPad Up
> > Save State Next Slot: Grab+DPad Left
> > Save State Prev Slot: Grab+DPad Right
> 
> Could you all delete `sd:/ultimate/TrainingModpack/training_modpack.toml` and retry?

Yep, it's working much better. Though, I thought when you said you switched the binds, you also removed the Grab up taunt and down taunt binds.

**Comment by jugeeya** [comment] 2023-07-13 04:27
Fixed by switching to menu slots in later releases.

**Closed by jugeeya** 2023-07-13 04:27 UTC
