### ISSUE TITLE
"Missed Tech Options" don't work with Snakes dthrow

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#156] opened 2020-09-02 15:05 UTC
Currently it's not possible to practice Snake dthrow tech chases as the CPU keeps lying down and acts way too late

**Comment by jugeeya** [comment] 2020-09-02 16:10
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/125

**Closed by jugeeya** 2020-09-02 16:10 UTC
