### ISSUE TITLE
Suggestion: Remapping Training Mode Reset Button Layout

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#401] opened 2022-11-03 11:33 UTC
The native Training Mode is reset by pressing L + A + R.

This has the problem  if you press for example Neutral Air Out of Shield with a shoulder button set to jump that it will reset the training mode if you don't let go of Shield.
You also reset the training mode when you go frame by frame and press R + A while holding L to advance the game.

For people who mainly use their R button to jump this is extremely inconvenient and makes the training mode useless in a lot of situations. 

Not a lot of people use that configuration for the Standard Gamecube Controller but the newest GCCPro (A GCC Mainboard inside a Pro Controller) has ZL and ZR mapped to L/R respectively and a good number of Pro Controller users jump with ZR.

In any way the current reset button layout was a dev oversight in my opinion. If they didn't remove the necessity of pressing jump for upB OoS or Upsmash they would've probably picked a different button combination.

Suggestion:
L + R then Start should work perfectly. (if possible)
L + R + Z would be ok as well, there shouldn't be many scenarios were someone presses all 3 buttons as once.
If it's possible to use more than 3 buttons: L + R + A + B (I can't think of a single situation where all 4 must be pressed at once)

Thanks for reading :)

**Comment by asimon-1** [comment] 2022-11-06 13:05
Duplicate of #40 and #404

**Closed by asimon-1** 2022-11-06 13:05 UTC
Labels: duplicate, enhancement
