### ISSUE TITLE
Account for more Mash Situations (bury, sleep, ...)

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#75] opened 2020-05-27 01:42 UTC
Mash Toggle doesn't work for
- Bury
- Yoshis Egg Lay
- Grab Release (incl. Inhales, Ridleys SideB etc.)
- Sleep Status
- Freeze Status
- Tripping Get-up

I personally need the Egg Lay thing, sooo 👀

**Comment by jugeeya** [comment] 2020-05-27 23:13
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/24 , but this one has a better list of what needs to be added.

**Closed** 2022-05-04 06:23 UTC
