### ISSUE TITLE
Input Delay Does Not Work with Pro Controller

### ISSUE THREAD

**Issue by R1XY** [jugeeya/UltimateTrainingModpack#489] opened 2023-02-23 11:01 UTC
I was trying to utilize the Input Delay Option to practice playing online, and I use the Pro Controller. I thought it was an installation mistake with the mod so I reinstalled it; to no avail.

I put the delay on 30, and switched to using the joycons; while they were on the Switch itself; and the inputs were delayed.

Is there anyway for the next possible update to support the Switch Pro Controller for Input Delay?

**Comment by Yikarur** [comment] 2023-02-23 13:25
I looked into your issue and it seems that the Delay is only applied to Port 1 of the Switch Controller Menu.

Make sure your controller is Port 1.
If you are in handheld / table top mode with the Joycons attached the Joycons are always considered Slot 1 so you have to remove them first.

**Comment by jugeeya** [comment] 2023-02-24 19:45
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/491 , I'll add this context there. Thanks!

**Closed by jugeeya** 2023-02-24 19:45 UTC
