### ISSUE TITLE
Suggestions: Left Stick affecting Jumps as well 

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#100] opened 2020-06-25 21:24 UTC
It's probably already in planning but I just wanted to drop the suggestions anyway

Linking the "Left Stick" to the Mash Option "Jump" as well, because Forward, Neutral and Backward Double Jump behave very differently in terms of hurtboxes and positioning to make combos work or to avoid combos. 
The neutral double jump might get hit in combos where a backward double jump avoids it so it's a pretty important option.

**Comment by jugeeya** [comment] 2020-08-12 20:31
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/71

**Closed by jugeeya** 2020-08-12 20:31 UTC
