### ISSUE TITLE
menu error during frame by frame

### ISSUE THREAD

**Issue by katykat5099** [jugeeya/UltimateTrainingModpack#257] opened 2021-09-08 15:39 UTC
You get a "page could not be displayed" when you try to open the mod's menu when you have frame by frame set.

Is this a bug or intentional? If its intentional I think a message saying "incompatible with frame by frame" would be a good implementation. 

Tested on latest beta release.

**Comment by jugeeya** [comment] 2022-11-02 18:41
Duplicate of #398

**Closed by jugeeya** 2022-11-02 18:41 UTC
